SELECT * FROM PERSON.PERSON;
SELECT FirstName FROM PERSON.PERSON;
SELECT DISTINCT FirstName FROM PERSON.PERSON;
SELECT DISTINCT LastName FROM PERSON.PERSON;

---SELECIONANDO INFORMAÇÕES UNICAS A TABELA ATRAVES DO DISTINCT------